apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:   # Este campo debe estar correctamente escrito
      - name: backend
        image: backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: PG_HOST
          value: "postgres-service"
        - name: PG_PORT
          value: "5432"
        - name: PG_DATABASE
          value: "ecommerce"
        - name: PG_USER
          value: "postgres"
        - name: PG_PASSWORD
          value: "linux"
